title: 朱寒冰
# url: "http://luohao.site"
# baseurl: "/luohao"

markdown: kramdown
#
#tracking_id: G-KC6ZFHG111

footer: No
footer_url: "https://github.com/icecoldwind"
footer_text: "Copy right @ Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "主页"
   link: "/"
#- name: "Publication"
#  link: "pub"
# - name: "Talk"
#  link: "talk"
 - name: "联系方式"
   link: "contact"

